# Basic functions for composing a table1
#' create_table1 show functions
#'
#' A collection of functions which create formated outputs for individual
#'  variables.
#'
#' @importFrom glue as_glue
#' @importFrom glue glue_col
#'
#' @param .x A vector corresponding to a column in a `tibble`.
#' @param .digits An integer number representing the number of decimals the
#'  output number should have.
#' @param ... For compatibility
#' @param .col_id,.description,.value,.valid_obs  Generated by `.show_*` functions.
#'  `.show_fns_output` collects and formats these values before outputing them
#'  as a list with four named elements of `glue_col` class.
#'
#' @returns
#' A list with four named elements:
#' *  .col_id
#' * .description
#' * .value
#' * .valid_obs
#'
#' @noRd
.show_nothing <- function(...){ # For variable without descriptive statistics
  NULL
}

.show_sample_size <- function(.x, ...) {
  .col_id      <- attr(.x, which = "short_label", exact = TRUE)
  .description <- "n"
  .value       <- .prettier_nums(.get_total_obs(.x))
  .valid_obs   <- ""

  .show_fns_output(.col_id, .description, .value, .valid_obs)
}

.show_period_range <- function(.x, ...) {
  .col_id       <- attr(.x, which = "short_label", exact = TRUE)
  .description  <- attr(.x, which = "short_label", exact = TRUE)
  .value        <- .get_period_range(.x)
  .valid_obs    <- .count_valid(.x)

  .show_fns_output(.col_id, .description, .value, .valid_obs)
}

.show_proportions <- function(.x, .digits, .exclude_NAs = TRUE) {
  if (.exclude_NAs) {
    .which <- "valids"
  } else {
    .which <- "all"
  }

  .col_id       <- attr(.x, which = "short_label", exact = TRUE)
  .description  <- .get_proportions_labels(.x)
  .value <- .get_proportions_values(.x, .digits, .which = .which)
  .valid_obs    <- .count_valid(.x)

  .show_fns_output(.col_id, .description, .value, .valid_obs)
}

.show_mean_sd <- function(.x, .digits) {
  .col_id       <- attr(.x, which = "short_label", exact = TRUE)
  .description  <- .get_mean_sd_labels(.x)
  .value        <- .get_mean_sd_values(.x, .digits)
  .valid_obs    <- .count_valid(.x)

  .show_fns_output(.col_id, .description, .value, .valid_obs)
}

.show_median_iqr <- function(.x, .digits) {
  .col_id       <- attr(.x, which = "short_label", exact = TRUE)
  .description  <- .get_median_iqr_labels(.x)
  .value        <- .get_median_iqr_values(.x, .digits)
  .valid_obs    <- .count_valid(.x)

  .show_fns_output(.col_id, .description, .value, .valid_obs)
}

.show_fns_output <-
  function(.col_id, .description, .value, .valid_obs) {
  .full_len <- max(length(.col_id), length(.description),
                   length(.value), length(.valid_obs))

  list(.col_id =
         glue::as_glue(c(glue::glue_col("{bold {.col_id}}"),
                         rep('',.full_len - length(.col_id)))),
       .description =
         glue::as_glue(c(glue::glue_col("{green {.description}}"),
                       rep('',.full_len - length(.description)))),
       .value =
         glue::as_glue(c(glue::glue_col("{blue {.value}}"),
                         rep('',.full_len - length(.value)))),
       .valid_obs =
         glue::as_glue(c(glue::glue_col("{red {.valid_obs}}"),
                         rep('',.full_len - length(.valid_obs)))))
  }

# Get and calc supporting functions -------------------------------------------
#' Get and calc helper functions to .show_* functions above
#'
#' These are helper functions that abstract extracting information or
#'  performing calculations. .get_* perform simple procedures or calculations
#'  while .calc_\* functions are called under .get_\* functions for slightly
#'  harder calculations.
#'
#' @importFrom glue glue_col
#' @importFrom purrr pmap_chr
#'
#' @param .x An R object corresponding to a tibble column.
#' @param .digits An integer indicating the number of decimal places the output
#'  should have.
#' @param .which A character string. Controls whether percentage should be
#'  calculated on complete observations or all observations.
#'  Should be one of: "all", "valid". If a character vector of size > 1 is
#'  passed, only the first element is used.
#' @param .x_lgl A logical vector. Usually either the output of !is.na(.x) or
#'  .x compared with one of its levels.
#'
#' @returns A character string of class `glue_col`.
#'
#' @noRd
#---- Proportions --------------------------------------------------------------
.get_proportions_labels <- function(.x) {
  .short_label <- attr(.x, which = "short_label", exact = TRUE)

  if (is.logical(.x[[1]])) {
    return(glue::glue_col("{.short_label} = Yes, n/d (%)"))
  }

  .x_lvls <- levels(.x[[1]])
  if (length(.x_lvls) == 2) {
    return(glue::glue_col("{.short_label} = {.x_lvls[1]}, n/d (%)"))
  }

  c(glue::glue_col("{.short_label}, n/d (%)"), paste0("--> ", levels(.x[[1]])))
}

.get_proportions_values <- function(.x, .digits, .which = c("all","valids")) {
  .prop_fn_lst <- c(all = .calc_proportions_all,
                    valids = .calc_proportions_valids)
  .prop_fn <- .prop_fn_lst[[.which[1]]]

  if (is.logical(.x)) {
    return(.prop_fn(.x, .digits))
  }

  .x_lvls <- levels(.x)

  if (length(.x_lvls) == 2) {
    return(.prop_fn(.x == .x_lvls[1] , .digits))
  }

  list(.ref_lvl = .x_lvls,
       .x = list(.x),
       .digits = .digits) %>%
    purrr::pmap_chr(function(.ref_lvl, .x, .digits)
      .prop_fn(.x == .ref_lvl, .digits)) %>%
    c("",.)
}

.calc_proportions_all <- function(.x_lgl, .digits) {
  .num <- sum(.x_lgl, na.rm = TRUE)
  .num_pretty <- .prettier_nums(.num)

  .den <- .get_total_obs(.x_lgl)
  .den_pretty <- .prettier_nums(.den)

  .pctg <- (.num/.den)*100
  .pctg_pretty <- .prettier_nums(.pctg, .digits)

  glue::glue_col("{.num_pretty}/{.den_pretty} ({.pctg_pretty}%)")
}

.calc_proportions_valids <- function(.x_lgl, .digits) {
  .num <- sum(.x_lgl, na.rm = TRUE)
  .num_pretty <- .prettier_nums(.num)

  .den <- sum(!is.na(.x_lgl))
  .den_pretty <- .prettier_nums(.den)

  .pctg <- (.num/.den)*100
  .pctg_pretty <- .prettier_nums(.pctg, .digits)

  glue::glue_col("{.num_pretty}/{.den_pretty} ({.pctg_pretty}%)")
}

.count_valid <- function(.x) {
  .calc_proportions_all(!is.na(.x), .digits = 0)
}
#---- Total counts -------------------------------------------------------------
.get_total_obs <- function(.x) {
  length(.x)
}

#---- Range -------------------------------------------------------------------
.get_period_range <- function(.x) {
  glue::glue_col("from: {min(.x, na.rm = TRUE)} to: {max(.x, na.rm = TRUE)}")
}

#---- Centrality and dispersion ------------------------------------------------
.get_mean_sd_labels <- function(.x) {
  .short_label <- attr(.x, which = "short_label", exact = TRUE)
  glue::glue_col("{.short_label}, mean ± SD")
}

.get_median_iqr_labels <- function(.x) {
  .short_label <- attr(.x, which = "short_label", exact = TRUE)
  glue::glue_col("{.short_label}, median [IQR]")
}

.get_mean_sd_values <- function(.x, .digits) {
  .x_avg <- mean(.x, na.rm = TRUE)
  .x_avg_pretty <- .prettier_nums(.x_avg, .digits)

  .x_sd <- sd(.x, na.rm = TRUE)
  .x_sd_pretty <- .prettier_nums(.x_sd, .digits)

  glue::glue_col("{.x_avg_pretty} ± {.x_sd_pretty}")
}

.get_median_iqr_values <- function(.x, .digits) {
  .x_med <- median(.x, na.rm = TRUE)
  .x_med_pretty <- .prettier_nums(.x_med, .digits)

  .x_lwr <- quantile(.x, p = .25, na.rm = TRUE)
  .x_lwr_pretty <- .prettier_nums(.x_lwr, .digits)

  .x_upr <- quantile(.x, p = .75, na.rm = TRUE)
  .x_upr_pretty <- .prettier_nums(.x_upr, .digits)

  glue::glue_col("{.x_med_pretty} [{.x_lwr_pretty}, {.x_upr_pretty}]")
}
