#' create_table1 test functions
#'
#' A collection of functions which perform inference testing for specific
#'  variables
#'
#' @importFrom glue as_glue
#' @importFrom glue glue_col
#'
#' @param .x A vector corresponding to a column in a `tibble`.
#' @param .digits An integer number representing the number of decimals the
#'  output number should have.
#' @param ... For compatibility
#' @param .col_id,.description,.value,.valid_obs  Generated by `.show_*` functions.
#'  `.show_fns_output` collects and formats these values before outputing them
#'  as a list with four named elements of `glue_col` class.
#'
#' @returns
#' A list with four named elements:
#' *  .col_id
#' * .description
#' * .value
#' * .valid_obs
#'
#' @noRd
.do_not_test <- function(...) {
  list(.pval_raw       = glue::glue_col(""),
       .pval_formatted = glue::glue_col(""))
}

.test_anova <- function(.col, .strata, .dataset, ...) {
  .test_formula <- as.formula(glue::glue("{.col} ~ {.strata}"))

  .pval <- summary(aov(.test_formula, data = .dataset))[[1]][["Pr(>F)"]][1]
  .pvals_out(.pval)
}

.test_kruskal <- function(.col, .strata, .dataset, ...) {
  .test_formula <- as.formula(glue::glue("{.col} ~ {.strata}"))

  .pval <-  kruskal.test(.test_formula, data = .dataset)[["p.value"]]
  .pvals_out(.pval)
}

.test_chisq <- function(.col, .strata, .dataset, ...) {
  if (is.logical(.dataset[[.col]])) {
    .num_lvls <- 2
  } else if (is.factor(.dataset[[.col]])) {
    .num_lvls <- length(levels(.dataset[[.col]]))
  }

  .pval <- chisq.test(table(.dataset[[.col]], .dataset[[.strata]]))[['p.value']]

  .pvals_out(.pval, .len_out = .num_lvls)
}

.pvals_out <- function(.pval, .len_out = 1, ...) {
  list(.pval_raw       = glue::as_glue(c(.pval,rep('', .len_out-1))),
       .pval_formatted = glue::as_glue(c(.pretty_pvals(.pval),rep('', .len_out-1))))
}

.pretty_pvals <- function(.pval, .alpha = 0.05) {
  if (.pval < 0.001) {
    return(glue::glue_col("< 0.001"))
  }

  if (.pval < .alpha) {
    return(glue::glue_col("{format(round(.pval,3), nsmall = 3)}"))
  }

  glue::glue_col("{silver {format(round(.pval,3), nsmall = 3)}}")
}

